services:
  api:
    image: batschauer97/projeto-emiteai-backend:2.0
    ports:
      - "8080:8080"
      - "11102:5432"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  postgres:
    image: postgres:16
    container_name: dbpostgres
    restart: always
    environment:
      POSTGRES_USER: dbsilva
      POSTGRES_PASSWORD: batschauer
      POSTGRES_DB: cadastropessoas
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dbsilva -d cadastropessoas" ]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./dados:/var/lib/rabbitmq/
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5